name: Release

on:
  push:
    tags:
      - "v*"  # Runs when you push a version tag like "v1.0.0"

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: publish-npm  # Wait for NPM publish before building Docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ecodesk-io/chat-widget:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

        